// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm_bM_TgUWT7oonHBuzoCCfgCRmbF9yPQ',
    appId: '1:402982696514:web:6c173751fbee662ecb5fdb',
    messagingSenderId: '402982696514',
    projectId: 'zevento-e8b17',
    authDomain: 'zevento-e8b17.firebaseapp.com',
    storageBucket: 'zevento-e8b17.firebasestorage.app',
    measurementId: 'G-V8BE6J9LHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZgSvbS1NZT18MjGODuwgIboFXRfxvKlw',
    appId: '1:402982696514:android:be9e0b4026124383cb5fdb',
    messagingSenderId: '402982696514',
    projectId: 'zevento-e8b17',
    storageBucket: 'zevento-e8b17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtWPLVsw-As949XIzxQOPKaz1Vk9l2HV8',
    appId: '1:402982696514:ios:c0f8c9480a5f92dfcb5fdb',
    messagingSenderId: '402982696514',
    projectId: 'zevento-e8b17',
    storageBucket: 'zevento-e8b17.firebasestorage.app',
    iosClientId: '402982696514-ooggcg2at5ngtodumqchco5nbrggooa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
